[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
collateralized_agents = "49aHwbzdT1iN8WYWdUZxrGoZpjSryyugMm4q9VTjXgSr"

[programs.devnet]
collateralized_agents = "49aHwbzdT1iN8WYWdUZxrGoZpjSryyugMm4q9VTjXgSr"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[test]
skip_local_validator = true
